"""The users table.

A mapping onto the table migration 0001 already created, not a definition of it. Every column,
constraint name and index name here reproduces what the migration wrote, so Alembic autogenerate
compares like with like instead of proposing to change a schema that is already correct.

Two things are deliberately *not* declared, and both are cases where declaring them would make
autogenerate or the test suite worse rather than better:

* The foreign key on `employee_id` to `employees.id`. It exists in the database, but a `ForeignKey`
  to a table with no model cannot be resolved the moment the metadata is used for DDL — which the
  unit tests do, on SQLite. It belongs here the day an `Employee` model lands. Until then any
  autogenerated migration touching this table needs reading before it is applied.
* The `failed_login_count >= 0` check constraint. Alembic does not compare check constraints, so
  omitting it costs nothing in drift; declaring it would cost accuracy, because the naming
  convention in `app.db.base` rewrites a named check constraint to `ck_users_<name>` and the
  migration created it as plain `failed_login_count_non_negative`.
"""

from __future__ import annotations

import enum
import uuid
from datetime import UTC, datetime

from sqlalchemy import Boolean, DateTime, Enum, Index, Integer, Text, UniqueConstraint, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.db.types import EncryptedString


class UserRole(enum.StrEnum):
    """The system roles (Requirement 2.1). Values match the `user_role` PostgreSQL enum.

    `operations_admin` is a full operational administrator with no financial visibility: it is in
    every operational role set but deliberately *not* in `app.core.authz.FINANCE_ROLES`, so the same
    redaction and finance-endpoint gating that hides money from a site manager hides it from this
    role too. It is not required or prompted for 2FA (absent from the sets below).
    """

    ADMIN = "admin"
    OPERATIONS_ADMIN = "operations_admin"
    SITE_MANAGER = "site_manager"
    ACCOUNTING = "accounting"
    EMPLOYEE = "employee"


class AppLanguage(enum.StrEnum):
    """Interface language, persisted per user (Requirement 21.4)."""

    HEBREW = "he"
    ENGLISH = "en"


#: Requirement 1.6: "2FA SHALL be mandatory for Administrator". A member of this set cannot use the
#: API until enrolment is complete — see `User.is_2fa_enrolment_required` and `app.api.deps`.
ROLES_REQUIRING_2FA = frozenset({UserRole.ADMIN})

#: Requirement 1.6's other half: the three console roles are *prompted* to enrol. Prompting is
#: advisory, so a site manager or accounting user who declines keeps working; the front end reads
#: `User.is_2fa_enrolment_prompted` to decide whether to ask. The employee role is absent: an
#: employee only scans a QR code from a phone, and a second factor there buys nothing worth the
#: friction.
ROLES_PROMPTED_FOR_2FA = frozenset({UserRole.ADMIN, UserRole.SITE_MANAGER, UserRole.ACCOUNTING})

#: Whether the 2FA enrolment obligation is enforced. True preserves Requirement 1.6 exactly; the app
#: factory lowers it from the `require_2fa_enrolment` setting so a deployment can relax the obligation
#: (a local-development convenience) without editing the role sets above. When false, both enrolment
#: properties below report false for every user, so the API gate and the front-end prompt both stand
#: down. A module-level flag rather than a settings read inside the property so the model stays free
#: of a config import and the unit tests can toggle it directly.
_ENFORCE_2FA = True


def set_2fa_enforcement(enabled: bool) -> None:
    """Turn the 2FA enrolment obligation on or off process-wide (see `_ENFORCE_2FA`)."""
    global _ENFORCE_2FA
    _ENFORCE_2FA = enabled


def _enum_column(enum_type: type[enum.Enum], name: str) -> Enum:
    """A PostgreSQL enum column storing member *values*.

    `values_callable` is the whole point: without it SQLAlchemy stores member *names*, so `ADMIN`
    would be written where the database's `user_role` type only accepts `admin`.
    """
    return Enum(
        enum_type,
        name=name,
        values_callable=lambda members: [member.value for member in members],
    )


def _utcnow() -> datetime:
    return datetime.now(UTC)


class User(Base):
    """A login. Distinct from an employee: `employee_id` links the two when the role is `employee`."""

    __tablename__ = "users"

    # Names given explicitly so they match migration 0001 exactly. The naming convention in
    # `app.db.base` only fills in names that were left unset, so an explicit name passes through.
    __table_args__ = (
        UniqueConstraint("username", name="uq_users_username"),
        UniqueConstraint("employee_id", name="uq_users_employee_id"),
        Index("ix_users_role", "role"),
    )

    # Python-side default so the caller can read `user.id` before the transaction commits; the
    # database's `gen_random_uuid()` remains the backstop for any writer that is not this ORM.
    id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4)

    username: Mapped[str] = mapped_column(Text, nullable=False)

    #: bcrypt only, work factor at least 12 (Requirement 1.3). See `app.core.security`.
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)

    role: Mapped[UserRole] = mapped_column(_enum_column(UserRole, "user_role"), nullable=False)

    #: Set for the employee role, linking a login to a person. Unique, so two logins cannot both act
    #: as the same employee. The database's foreign key is not declared here — see the module note.
    employee_id: Mapped[uuid.UUID | None] = mapped_column(Uuid(as_uuid=True), nullable=True)

    #: Deactivation is a status change, never a delete, so historical attribution survives. Setting
    #: this false must be accompanied by a `token_version` bump, or tokens already issued keep
    #: working (Requirement 1.4).
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    #: The shared secret behind the TOTP codes of Requirement 1.5. Encrypted at rest by the column
    #: type: the attribute is plaintext to the service layer, the column holds ciphertext. Named
    #: without the `_encrypted` suffix that the column carries, matching how the design distinguishes
    #: a stored column from the value a service sees.
    totp_secret: Mapped[str | None] = mapped_column("totp_secret_encrypted", EncryptedString, nullable=True)

    #: A secret that has been issued but not yet proven to work. Enrolment writes here, verification
    #: promotes it to `totp_secret` and clears it, and nothing else ever reads it — a login is only
    #: ever checked against the proven secret.
    #:
    #: The second column is what makes re-enrolment safe. With one column, issuing a new secret to a
    #: user who already has 2FA enabled destroys the working one the instant the request is made, so
    #: a user who closes the tab before scanning the QR code has locked themselves out of their own
    #: account. Holding the unproven secret to one side means the old authenticator keeps working
    #: until the new one is demonstrated, and an abandoned enrolment costs nothing.
    totp_pending_secret: Mapped[str | None] = mapped_column(
        "totp_pending_secret_encrypted", EncryptedString, nullable=True
    )

    is_2fa_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    #: Whether the login owes a password change before it may use the rest of the API. Set true for a
    #: non-administrator on creation (see `app.services.user.create_user`) and backfilled true for
    #: existing non-admins by migration 0005, so the person who owns the account picks their own
    #: password rather than keeping the one an administrator chose. Read directly by the gate in
    #: `app.api.deps.get_enrolled_user`, which also exempts the admin role; `default=False` keeps the
    #: bootstrap admin and any admin-role login clear of the obligation. Cleared by
    #: `app.services.auth.change_password`. A plain column, not a `_ENFORCE_2FA`-style module flag:
    #: the obligation is per-row state, so there is no process-wide global to reset between tests.
    must_change_password: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    #: Failed attempts in the current window, and when that window closes. The pair encodes both the
    #: 15-minute window and the lock of Requirement 1.7; `app.services.auth` owns the rules and
    #: explains why one timestamp can serve both.
    failed_login_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    locked_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    language: Mapped[AppLanguage] = mapped_column(
        _enum_column(AppLanguage, "app_language"), nullable=False, default=AppLanguage.HEBREW
    )

    #: Bumped on deactivation, on password change, on logout and on every refresh rotation. Every
    #: issued token carries the version it was minted under, so a bump invalidates outstanding tokens
    #: immediately without the server keeping session state (Requirement 20.8).
    token_version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    @property
    def is_2fa_enrolment_required(self) -> bool:
        """Whether this user owes the system an enrolment before they may use the rest of the API.

        Requirement 1.6. Read by `app.api.deps.get_enrolled_user`, which is the gate, and returned on
        `GET /auth/me` so the front end can send the user straight to the enrolment screen instead of
        letting them discover the block one failed request at a time.
        """
        return _ENFORCE_2FA and self.role in ROLES_REQUIRING_2FA and not self.is_2fa_enabled

    @property
    def is_2fa_enrolment_prompted(self) -> bool:
        """Whether the front end should offer enrolment.

        True for a console role that has not enrolled, including an administrator — for whom it is
        also mandatory. Declining is allowed for everyone this is true of *except* an administrator,
        and `is_2fa_enrolment_required` is what says which case the caller is in.
        """
        return _ENFORCE_2FA and self.role in ROLES_PROMPTED_FOR_2FA and not self.is_2fa_enabled

    def __repr__(self) -> str:
        return f"User({self.username!r} role={self.role} active={self.is_active})"
