"""Excel rendering with typed cells (Requirement 19.1).

The one claim this renderer exists to make true: a number lands in the workbook as a number and a
date as a date, so accounting can sum a column and sort by day. openpyxl already writes the right XML
type for a Python `int`, `Decimal`, `date` or `datetime` — the work here is to hand it the value with
its Python type intact (never a pre-formatted string) and to set a number format so the cell *reads*
as money or hours while still *being* a number.

A `Decimal` is passed straight through: openpyxl serialises it as a numeric cell, and doing the
`float()` conversion here would reintroduce the binary-rounding error the whole system avoids by using
`Decimal` for money. The number format is a display mask laid over the stored number; it changes how
`332.5` looks, not what it is, so the cell still sums.

Hebrew (Requirement 19.3): a spreadsheet is not laid out left-to-right or right-to-left the way a
page is — each cell holds its own text and the application renders Hebrew correctly by default. The
sheet's `sheet_view.rightToLeft` is set for a Hebrew document so the columns run right-to-left, which
is the RTL affordance a spreadsheet has.
"""

from __future__ import annotations

import io

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

from app.export.document import Cell, CellKind, ExportDocument, ExportTable

#: Number-format masks per kind. Money and hours are two-place decimals; the money mask carries the
#: shekel sign so the cell reads as currency while staying numeric. Integers show with a thousands
#: separator. Dates use ISO-like masks that a spreadsheet still treats as real dates.
_NUMBER_FORMATS: dict[CellKind, str] = {
    CellKind.INTEGER: "#,##0",
    CellKind.MONEY: '#,##0.00\u00a0"\u20aa"',
    CellKind.HOURS: "#,##0.00",
    CellKind.DATE: "dd/mm/yyyy",
    CellKind.DATETIME: "dd/mm/yyyy hh:mm",
}

_HEADER_FONT = Font(bold=True)
_TITLE_FONT = Font(bold=True, size=14)
_TOTALS_FONT = Font(bold=True)


def to_xlsx(document: ExportDocument) -> bytes:
    """Render a document to an `.xlsx` workbook and return its bytes.

    One sheet holds the whole document: the title, the provenance stamp (Requirement 19.4), then each
    table with its headers, typed rows and totals. The bytes are what the export service stores and the
    client downloads; nothing here touches storage or the request.
    """
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = _sheet_title(document)
    if document.is_rtl():
        sheet.sheet_view.rightToLeft = True

    row = _write_header(sheet, document)
    for table in document.tables:
        row = _write_table(sheet, document, table, start_row=row) + 1

    _autosize(sheet)
    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def _sheet_title(document: ExportDocument) -> str:
    """A worksheet name Excel accepts: 31 characters, none of the reserved punctuation."""
    title = document.localized_title()
    for bad in "[]:*?/\\":
        title = title.replace(bad, " ")
    return title.strip()[:31] or "Export"


def _write_header(sheet: Worksheet, document: ExportDocument) -> int:
    """The title and provenance stamp block. Returns the next free row (1-based)."""
    row = 1
    sheet.cell(row=row, column=1, value=document.localized_title()).font = _TITLE_FONT
    row += 2

    stamp = document.stamp
    for label, value in _stamp_lines(document):
        sheet.cell(row=row, column=1, value=label).font = _HEADER_FONT
        sheet.cell(row=row, column=2, value=value)
        row += 1
    _ = stamp
    return row + 1


def _stamp_lines(document: ExportDocument) -> list[tuple[str, str]]:
    """The stamp rendered as label/value pairs (Requirement 19.4), localized minimally.

    The labels differ by language; the values are already display text. Kept here rather than in the
    document so the two renderers do not each reinvent the wording.
    """
    en = document.language == "en"
    stamp = document.stamp
    lines: list[tuple[str, str]] = [
        ("Period" if en else "\u05ea\u05e7\u05d5\u05e4\u05d4", stamp.period_label),
        (
            "Generated at" if en else "\u05d4\u05d5\u05e4\u05e7 \u05d1\u05ea\u05d0\u05e8\u05d9\u05da",
            stamp.generated_at.strftime("%d/%m/%Y %H:%M"),
        ),
        (
            "Generated by" if en else "\u05d4\u05d5\u05e4\u05e7 \u05e2\u05dc \u05d9\u05d3\u05d9",
            stamp.generated_by,
        ),
    ]
    for label, value in stamp.filters:
        lines.append((label, value))
    if stamp.currency:
        lines.append(("Currency" if en else "\u05de\u05d8\u05d1\u05e2", stamp.currency))
    return lines


def _write_table(
    sheet: Worksheet, document: ExportDocument, table: ExportTable, *, start_row: int
) -> int:
    """Write one table's optional title, header row, data rows and totals. Returns the last row used."""
    row = start_row
    table_title = _table_title(document, table)
    if table_title:
        sheet.cell(row=row, column=1, value=table_title).font = _HEADER_FONT
        row += 1

    for column_index, column in enumerate(table.columns, start=1):
        header = column.header_en if document.language == "en" else column.header
        header_cell = sheet.cell(row=row, column=column_index, value=header)
        header_cell.font = _HEADER_FONT
    row += 1

    for data_row in table.rows:
        _write_cells(sheet, row, data_row)
        row += 1

    if table.totals is not None:
        _write_cells(sheet, row, table.totals, font=_TOTALS_FONT)

    return row


def _table_title(document: ExportDocument, table: ExportTable) -> str | None:
    if document.language == "en":
        return table.title_en or table.title
    return table.title


def _write_cells(
    sheet: Worksheet,
    row: int,
    cells: list[Cell] | tuple[Cell, ...],
    *,
    font: Font | None = None,
) -> None:
    for column_index, one in enumerate(cells, start=1):
        target = sheet.cell(row=row, column=column_index)
        # The value keeps its Python type: an int stays an int, a Decimal stays a Decimal, a date
        # stays a date. This is the whole of Requirement 19.1 — openpyxl writes the numeric or date
        # XML type from the Python type, so the cell is a real number or date, not text.
        target.value = one.value
        number_format = _NUMBER_FORMATS.get(one.kind)
        if number_format is not None and one.value is not None:
            target.number_format = number_format
        if one.kind is CellKind.TEXT:
            target.alignment = Alignment(wrap_text=True, vertical="top")
        if font is not None:
            target.font = font


def _autosize(sheet: Worksheet) -> None:
    """Widen columns to their content, capped so a long note does not run off the page."""
    widths: dict[int, int] = {}
    for row in sheet.iter_rows():
        for cell_obj in row:
            if cell_obj.value is None:
                continue
            length = len(str(cell_obj.value))
            widths[cell_obj.column] = max(widths.get(cell_obj.column, 0), length)
    for column_index, width in widths.items():
        sheet.column_dimensions[get_column_letter(column_index)].width = min(max(width + 2, 10), 50)
