"""The audit writer against the real schema.

The writer's behaviour is covered by unit tests on SQLite, which is fast and proves the logic. What
SQLite cannot prove is that the `ChangeLog` model still describes the table migration 0001 actually
created — and a model that has drifted from its table fails at runtime while every unit test stays
green. That is what these tests are for: the model matches the migrated table, and a write through
the ORM lands in it.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.models.change_log import ChangeLog
from app.services.audit import AuditContext, record_change

# `changed_by_user_id` is left out of the round-trip: it is a foreign key to `users`, and creating a
# user needs the auth task's password hashing. The null case is the one that matters here anyway —
# a shift closed by a site transition has no acting user (Requirement 11.8).
SYSTEM_CONTEXT = AuditContext(request_id="req-integration")


def test_model_columns_match_the_migrated_table(migrated_engine: sa.Engine) -> None:
    """Drift here is invisible to the unit tests and fatal at runtime."""
    reflected = sa.Table("change_logs", sa.MetaData(), autoload_with=migrated_engine)

    assert {column.name for column in ChangeLog.__table__.columns} == {
        column.name for column in reflected.columns
    }
    for column in ChangeLog.__table__.columns:
        assert column.nullable == reflected.columns[column.name].nullable, (
            f"{column.name} is nullable={column.nullable} on the model and "
            f"nullable={reflected.columns[column.name].nullable} in the database"
        )


def test_model_indexes_match_the_migrated_table(migrated_engine: sa.Engine) -> None:
    """So an autogenerated migration does not propose dropping and recreating them."""
    reflected = sa.Table("change_logs", sa.MetaData(), autoload_with=migrated_engine)
    assert {index.name for index in ChangeLog.__table__.indexes} <= {
        index.name for index in reflected.indexes
    }


def test_a_write_through_the_orm_lands_in_the_table(db: sa.Connection) -> None:
    """The whole path: model, types, session, PostgreSQL. Rolled back by the fixture."""
    entity_id = uuid.uuid4()
    with Session(bind=db, expire_on_commit=False) as session:
        record_change(
            session,
            entity_type="time_entries",
            entity_id=entity_id,
            field="check_out_at",
            old_value=datetime(2025, 8, 30, 15, 30, tzinfo=UTC),
            new_value=datetime(2025, 8, 30, 16, 0, tzinfo=UTC),
            context=SYSTEM_CONTEXT,
            reason="forgot to scan",
        )
        session.flush()

    row = db.execute(
        sa.text(
            "SELECT entity_type, field, old_value, new_value, reason, request_id, "
            "changed_by_user_id, changed_at FROM change_logs WHERE entity_id = :id"
        ),
        {"id": entity_id},
    ).one()
    assert row.entity_type == "time_entries"
    assert row.field == "check_out_at"
    assert row.old_value == "2025-08-30T15:30:00+00:00"
    assert row.new_value == "2025-08-30T16:00:00+00:00"
    assert row.reason == "forgot to scan"
    assert row.request_id == "req-integration"
    assert row.changed_by_user_id is None
    # The column is timestamptz, so what comes back is aware and comparable without guesswork.
    assert row.changed_at.tzinfo is not None


def test_the_writer_does_not_commit_the_callers_transaction(db: sa.Connection) -> None:
    """Requirement 13.2 against the real database: the row is visible inside the transaction and gone
    once it rolls back. The `db` fixture rolls back, so the assertion is that nothing escaped it."""
    entity_id = uuid.uuid4()
    savepoint = db.begin_nested()
    with Session(bind=db, expire_on_commit=False) as session:
        record_change(
            session,
            entity_type="employees",
            entity_id=entity_id,
            field="position",
            old_value="Labourer",
            new_value="Foreman",
            context=SYSTEM_CONTEXT,
        )
        session.flush()
        assert (
            db.execute(
                sa.text("SELECT count(*) FROM change_logs WHERE entity_id = :id"), {"id": entity_id}
            ).scalar_one()
            == 1
        )
    savepoint.rollback()

    assert (
        db.execute(
            sa.text("SELECT count(*) FROM change_logs WHERE entity_id = :id"), {"id": entity_id}
        ).scalar_one()
        == 0
    )
