"""The mapped models describe the migrated schema and nothing else.

`app.models` maps onto tables migration 0001 created. If a model drifts from the migration — a column
declared with the wrong nullability, a constraint named differently, a type that does not match — the
first symptom is an autogenerated migration proposing to "fix" a schema that was already correct, and
by then someone has usually applied it.

So this asks Alembic the question directly: given the live migrated database and the models, what
would autogenerate propose? For the mapped tables the answer has to be "nothing", with one documented
exception that is recorded here rather than discovered later.
"""

from __future__ import annotations

from typing import Any

import sqlalchemy as sa
from sqlalchemy.engine import Engine

from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from app.db.base import Base

#: Tables that have a model. Everything else in the schema is reported as an unmapped table, which is
#: expected until the remaining models land, so the comparison is narrowed to these.
MAPPED_TABLES = {"users", "change_logs", "user_sites"}

#: Foreign keys the database has and the models cannot yet declare: `users.employee_id` and
#: `user_sites.site_id` both point at tables with no model, and a `ForeignKey` to an unmapped table
#: fails to resolve the moment the metadata is used for DDL — which the unit tests do, on SQLite.
#: Recorded here so each exception is visible and so this test starts failing the day it is no longer
#: needed.
KNOWN_DRIFT = {("remove_fk", "users"), ("remove_fk", "user_sites")}


def _diff_signature(diff: Any) -> tuple[str, str | None]:
    """Reduce one autogenerate diff to `(kind, table)`.

    Alembic's diff entries are tuples of varying shapes, and a `modify_*` group arrives as a list of
    them. Only the kind and the table are needed to decide whether a difference is expected.
    """
    if isinstance(diff, list):
        return _diff_signature(diff[0])

    kind = diff[0]
    match kind:
        case "add_table" | "remove_table":
            return kind, diff[1].name
        case "add_column" | "remove_column":
            return kind, diff[2]
        case "add_index" | "remove_index" | "add_constraint" | "remove_constraint" | "add_fk" | "remove_fk":
            return kind, diff[1].table.name
        case _:
            # `modify_nullable`, `modify_type`, `modify_default`: (kind, schema, table, column, ...).
            return kind, diff[2] if len(diff) > 2 else None


def _diffs(engine: Engine) -> list[Any]:
    with engine.connect() as connection:
        return compare_metadata(
            MigrationContext.configure(connection, opts={"compare_type": True}), Base.metadata
        )


def test_autogenerate_proposes_nothing_for_the_mapped_tables(migrated_engine: Engine) -> None:
    """The models declare exactly what the migration created."""
    signatures = {
        signature
        for signature in (_diff_signature(diff) for diff in _diffs(migrated_engine))
        if signature[1] in MAPPED_TABLES
    }
    assert signatures - KNOWN_DRIFT == set()


def test_the_change_log_foreign_key_to_users_is_declared(migrated_engine: Engine) -> None:
    """The one piece of drift the `User` model made it possible to remove.

    Stated as its own test because the previous one passes whether the constraint is declared or not:
    an undeclared foreign key that the database has would show up as another `remove_fk`, and a reader
    scanning `KNOWN_DRIFT` should not have to work out which is which.
    """
    constraint = next(iter(Base.metadata.tables["change_logs"].foreign_key_constraints), None)
    assert constraint is not None
    assert constraint.name == "fk_change_logs_changed_by_user_id_users"
    assert {column.name for column in constraint.columns} == {"changed_by_user_id"}

    with migrated_engine.connect() as connection:
        in_database = sa.inspect(connection).get_foreign_keys("change_logs")
    assert [fk["name"] for fk in in_database] == [constraint.name]
