"""Declarative base. Models import from here so Alembic autogenerate sees one metadata object."""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Constraints are named by convention so a hand-written migration and a later autogenerated one
# agree on what a constraint is called. Without this, autogenerate sees PostgreSQL's own names on
# one side and SQLAlchemy's unnamed constraints on the other, and proposes dropping and recreating
# things that never changed. The primary-key pattern deliberately reproduces PostgreSQL's default
# (`<table>_pkey`) rather than inventing a new one, so existing tables need no rename.
NAMING_CONVENTION = {
    "pk": "%(table_name)s_pkey",
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
}


class Base(DeclarativeBase):
    """Base class for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
